// ============================================================
// ROM / SRAM Black-Box Stubs for Synthesis — v3
//
// v3 vs v2:
//   mfn_weight_rom_v3: 12-read-port ROM (one addr per SA row)
//     — academic wide model, cannot be synthesized; black box.
//   bias_rom, prelu_rom, layer_config_rom: unchanged from v2
//   mfn_psum_sram + OpenRAM macros: identical to v2 (reused)
// ============================================================

// Weight ROM v3: 12 independent read ports (one per SA row).
// Each addr[r] reads SA_COLS=12 consecutive weights → wgt_out[r][0..11].
module mfn_weight_rom_v3 #(
    parameter int DWIDTH   = 16,
    parameter int MEM_BITS = 20,
    parameter int SA_ROWS  = 12,
    parameter int SA_COLS  = 12
)(
    input  logic [MEM_BITS-1:0]      addr    [SA_ROWS],
    output logic signed [DWIDTH-1:0] wgt_out [SA_ROWS][SA_COLS]
);
endmodule

module mfn_bias_rom #(parameter int DWIDTH = 32)(
    input  logic [13:0]              addr,
    output logic signed [DWIDTH-1:0] bias_out
);
endmodule

module mfn_prelu_rom #(parameter int DWIDTH = 16)(
    input  logic [13:0]              addr,
    output logic signed [DWIDTH-1:0] prelu_out
);
endmodule

module mfn_layer_config_rom #(parameter int ADDR_WIDTH = 6)(
    input  logic                  clk,
    input  logic [ADDR_WIDTH-1:0] addr,
    output logic [63:0]           data_out
);
endmodule

// ── OpenRAM leaf SRAM stubs (identical to v2) ────────────────
// psum SRAM interface unchanged: 512×40-bit, 1RW+1R / 1RW.
module sram_psum_a_1rw1r0w_40_512_freepdk45 (
    input        clk0, csb0, web0,
    input  [4:0] wmask0,
    input  [8:0] addr0,
    input  [39:0] din0,
    output [39:0] dout0,
    input        clk1, csb1,
    input  [8:0] addr1,
    output [39:0] dout1
);
endmodule

module sram_psum_b_1rw0r0w_40_512_freepdk45 (
    input        clk0, csb0, web0,
    input  [4:0] wmask0,
    input  [8:0] addr0,
    input  [39:0] din0,
    output [39:0] dout0
);
endmodule

// mfn_psum_sram: structural wrapper for synthesis / P&R.
// v3 uses ONLY psum SRAM_A — the controller never drives we_b (psum port B
// was a v2 dual-MAC artifact).  SRAM_A (1RW1R) covers write-A + read-A +
// read-C; SRAM_B is dropped → one fewer macro, ~33K um² saved.
// RTL simulation uses sv3/mfn_psum_sram.sv (behavioral) instead.
module mfn_psum_sram #(
    parameter int AWIDTH = 40,
    parameter int DEPTH  = 512,
    parameter int ABITS  = 9
)(
    input  logic              clk,
    input  logic              we_a,
    input  logic [ABITS-1:0]  waddr_a,
    input  logic [AWIDTH-1:0] wdata_a,
    input  logic              we_b,
    input  logic [ABITS-1:0]  waddr_b,
    input  logic [AWIDTH-1:0] wdata_b,
    input  logic [ABITS-1:0]  raddr_a,
    output logic [AWIDTH-1:0] rdata_a,
    input  logic [ABITS-1:0]  raddr_b,
    output logic [AWIDTH-1:0] rdata_b,
    input  logic [ABITS-1:0]  raddr_c,
    output logic [AWIDTH-1:0] rdata_c
);
    sram_psum_a_1rw1r0w_40_512_freepdk45 u_sram_a (
        .clk0   (clk),
        .csb0   (1'b0),
        .web0   (~we_a),
        .wmask0 (5'b11111),
        .addr0  (we_a ? waddr_a : raddr_a),
        .din0   (wdata_a),
        .dout0  (rdata_a),
        .clk1   (clk),
        .csb1   (1'b0),
        .addr1  (raddr_c),
        .dout1  (rdata_c)
    );

    // psum SRAM_B removed (v3 never uses port B).  we_b/waddr_b/wdata_b/raddr_b
    // are left unconnected; rdata_b is tied off.
    assign rdata_b = '0;
endmodule

// ── act_buf SRAM leaf cell (1RW, 192-bit × 64 words, v3+ opt④) ──────────────
// Generated by OpenRAM for FreePDK45 (freepdk45_sram_act_buf_192x64.py).
// word_size=192 (12 channels × 16-bit), num_words=64, write_size=16
//   → wmask0 is 12 bits (one per channel lane).
// Instantiated inside mfn_act_buf (u_act_buf/u_sram).
// Synthesis black-box: dont_touch on u_act_buf/u_sram in synthesis_v3.tcl.
// Simulation: behavioral model sv3/sram_act_buf_1rw0r0w_192_64_freepdk45.sv.
// P&R: LEF/.lib from OpenRAM (macro 639.37 × 152.365 um).
module sram_act_buf_1rw0r0w_192_64_freepdk45 (
    input         clk0, csb0, web0,
    input  [11:0] wmask0,   // 12 lane mask (192 bits / write_size 16)
    input  [5:0]  addr0,    // 6-bit: ceil(log2(64))
    input  [191:0] din0,
    output [191:0] dout0
);
endmodule
